name: Android branch build

on:

  push:

    branches:

      - '*design*'

jobs:

  build_branch:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3

      with:

        distribution: 'temurin'

        java-version: '17'

    - uses: gradle/gradle-build-action@v2

    - name: Checkout submodules

      run: git submodule update --init --recursive

    - name: Build, test, and lint

      run: ./gradlew clean assembleAlphaRelease

    - name: List

      run: ls -alR ./app/build/outputs/apk/

    
    - uses: actions/upload-artifact@v2

      name: Upload APK artifact

      with:

        name: *.apk

        path: ./app/build/outputs/apk/
